# Generated by Django 5.0.4 on 2024-11-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PREP', 'En preparación'), ('LIST', 'Listo para entrega'), ('ENTR', 'Entregado'), ('PAGAR', 'Quieren pagar')], default='PREP', max_length=6),
        ),
    ]
