# Generated by Django 5.0.4 on 2024-11-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
